# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
  - go mod tidy
builds:
- id: gitlab
  binary: gitlab
  env:
  - CGO_ENABLED=0
  main: ./main.go
  goos:
  - darwin
  - linux
  goarch:
  - amd64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
  files:
  - README.md
  - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
    - go mod tidy
nfpms:
- id: deb
  package_name: gitlab
  formats:
  - deb
- id: apk
  package_name: gitlab
  formats:
  - apk
publishers:
- name: deb
  ids:
  - deb
  cmd: hack/publish_deb {{ abs .ArtifactPath }} {{ .ArtifactName }} {{ .Arch }}
  env:
  - ARTIFACTORY_USERNAME={{ .Env.ARTIFACTORY_USERNAME }}
  - ARTIFACTORY_SECRET={{ .Env.ARTIFACTORY_SECRET }}
- name: apk
  ids:
  - apk
  cmd: hack/publish_apk {{ abs .ArtifactPath }} {{ .ArtifactName }} {{ .Arch }}
  env:
  - ARTIFACTORY_USERNAME={{ .Env.ARTIFACTORY_USERNAME }}
  - ARTIFACTORY_SECRET={{ .Env.ARTIFACTORY_SECRET }}
brews:
- name: gitlab
  tap:
    owner: bottlerocketlabs
    name: homebrew-apps
    token: "{{ .Env.HOMEBREW_GITHUB_TOKEN }}"
  folder: Formula
  homepage:  https://github.com/bottlerocketlabs/gitlab
  description: Create gitlab issue in project linked to current git repository using git editor and selecting optional template
  license: BSD-3-clause
  test: |
    system "#{bin}/gitlab -help"
  dependencies:
  - name: go
  install: |-
    bin.install "gitlab"
